export const COLOR = {
  primary: "#60DBFB",
  secondary: "#20232A",
  accent: "#0093DD",
};

export const APP = {
  url: "https://odaratv.com.ng",
  name: "Odara TV",
  alias: "Odara TV&reg;",
  thumbnail: "/social-preview.png",
  domain: "odaratv.com.ng",
  author: "Tugbeh Emmanuel",
  owner: "HWP Labs",
  description: "Tech News, Movies & TV Shows",
  keywords: [
    "odara",
    "odara tv",
    "download",
    "youtube",
    "technology",
    "tech",
    "scifi",
    "sci-fi",
    "sci fi",
    "news",
    "tech news",
    "movies",
    "tech movies",
    "tv shows",
    "tv series",
    "shows",
    "series",
    "hwp",
    "hwp labs",
    "tugbeh",
    "emmanuel tugbeh",
  ],
  copyright:
    '<address class="copy" id="end"> Copyright &copy; 2017 <a href="https://www.facebook.com/hwplabs" target="_blank" rel="author" title="Webmaster">HWP Labs.</a><cite>CRBN 658815</cite></address>',
  build: "6.18.3.23",
  created_at: "2023-03-18",
  updated_at: "2023-03-19",
};
